const labels: Record<string, string> = {
  healthy: '正常', ok: '正常', degraded: '存在异常', disabled: '未启用', error: '失败',
  paused: '已暂停', not_configured: '尚未配置', stale: '扫描状态已过期', complete: '完整扫描完成',
  pending: '等待处理', baseline_pending: '待基线审核', managed: '同步管理', detached: '脱离管理',
  draft: '草稿', published: '已发布', unpublished: '已下架', archived: '已归档',
  running: '运行中', queued: '排队', discovering: '扫描中', scanning: '扫描中', schema: '核验来源配置',
  planned: '预览完成', applying: '应用中', apply_partial: '应用已读取的部分结果', apply_complete: '应用完整扫描结果',
  bootstrap: '审核与接管', finished: '已结束', completed: '完成', succeeded: '成功',
  completed_with_errors: '已完成，部分项目失败或被阻止', failed: '失败', partial_failed: '部分失败',
  abandoned: '运行中断（工作租约已失效）', cancelled: '已取消',
  unchanged: '未变化', created: '新增', updated: '更新', blocked: '已阻止',
  retained: '保留上次成功资料', state_only: '仅处理状态与公开限制',
  preview: '页面变更预览', catalog_preview: '主题目录预览', bound: '已绑定', conflict: '绑定冲突', invalid: '失效绑定',
  adopted: '已确认接管', already_adopted: '已接管，无需重复处理',
  catalog_prepare: '主题目录准备', dry_run: '预览', sync: '同步', bootstrap_apply: '审核后接管', bootstrap_preview: '历史基线审核预览'
};
const reasons: Record<string, string> = {
  source_identity_conflict: 'Notion 页面与已有文章来源身份冲突，请先核对文章和页面身份',
  needs_revalidation: '等待重新同步核验来源；核验通过后再决定是否公开',
  publication_hold: '博客已本地紧急下架；解除后仍需重新同步核验来源',
  public_url_missing: 'Notion 页面没有公开阅读链接，请先在来源端检查公开设置',
  not_published: '来源尚未发布，暂不创建公开文章',
  native_archived: 'Notion 页面已归档，不能公开',
  in_trash: 'Notion 页面已移入回收站，不能公开',
  native_archived_or_in_trash: 'Notion 页面已归档或移入回收站，不能公开',
  out_of_scope: '页面已离开配置的来源范围，需重新核验来源',
  source_disabled: '来源已停用，本次不应用变更',
  source_in_trash: 'Notion 来源已移入回收站，请先恢复来源并重新核验',
  source_schema_changed: '来源属性或状态选项已变化，请核对来源配置并重新同步',
  source_module_unconfigured: '来源尚未绑定博客模块，请先配置模块',
  source_unavailable: '来源暂不可读取，请检查访问权限或稍后重试',
  transport_error: '读取来源失败，请检查连接并稍后重试',
  rate_limited: 'Notion 请求受到限流，请等待冷却后重试',
  unknown_state: '来源发布状态为空或无法识别，请核对状态选项配置',
  invalid_field: '来源字段值无效，请检查标题、主题、标签等属性',
  invalid_metadata: '来源资料不符合要求，请核对页面属性',
  metadata_invalid: '来源资料或目录位置无效，请核对页面属性和主题绑定',
  catalog_binding_invalid: '主题绑定已失效，请选择正确章节并重新预览',
  catalog_directory_hidden: '绑定的模块或章节已隐藏，文章暂不能公开',
  catalog_same_name_conflict: '存在同名章节，请核对并调整主题绑定',
  module_binding_changed: '来源模块绑定已变化，请重新确认主题对应的章节',
  historical_match_requires_confirmation: '等待审核当前博客状态并回填确认，网页不会自动接管',
  historical_identity_conflict: '历史文章来源身份冲突，需要人工核对后再接管',
  historical_match_ambiguous: '发现多个可能匹配的历史文章，需要人工确认',
  local_state_unknown: '历史文章状态无法识别，需要人工审核',
  notion_state_conflict: 'Notion 状态与历史博客状态冲突，请先审核当前状态',
  native_archived_requires_review: 'Notion 页面已归档，需要人工审核后再决定是否接管',
  state_not_published: '本站状态尚未发布，前台不可见',
  article_not_registered: '尚未收录为本站文章，请等待受控同步处理',
  catalog_invalid: '目录关系不完整，请检查所属模块、章节和子章节',
  catalog_disabled: '所属模块、章节或子章节已停用，前台不可见',
  article_missing: '关联的本站文章不存在，请核对历史绑定',
  target_disabled: '目标来源已停用，需重新核验归属',
  target_schema_changed: '目标来源的字段映射已变化，需重新核验',
  bound: '沿用已确认的主题绑定',
  would_create: '预览：将为新主题创建章节',
  would_rename: '预览：将按 Notion 主题名称更新已绑定章节'
};
export const syncStateLabel = (value?: string) => value ? labels[value] || value : '—';
// Unknown diagnostics remain intact for troubleshooting; audit JSON is never translated.
export const syncReasonLabel = (value?: string) => value ? reasons[value] || value : '—';
