name: buildx-check
on: workflow_dispatch
jobs:
  xbuild:
    runs-on: [self-hosted, macmini, prod]  # 如果没加标签，用 [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build amd64 test image
        run: |
          cat > Dockerfile <<'EOF'
          FROM alpine:3.20
          CMD ["sh","-c","uname -m && echo OK"]
          EOF
          docker buildx build --platform linux/amd64 -t arch-test:amd64 --load .
          docker run --rm arch-test:amd64
